# -*- coding: utf-8 -*-
"""Copy of ParseEDFAndTXTToCSV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GWfhUPexMQllExx0rc6F8mk-A2Vu_toh

## Parse EDF and .txt with annotations to a CSV file

"""## Load CSV"""

import pandas as pd
df = pd.read_csv("n1_data_and_annotations.csv")
df.head(4)

# MIN MAX SCALER #

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
new_df = df.iloc[:,:-2]
#scaler.fit(new_df)
#scaler.data_max_
norm = scaler.fit_transform(new_df)
cols = df.columns
norm = pd.DataFrame(norm)
norm["times"]=df[["times"]]
norm['sleepstage'] = df[["sleepstage"]]
norm.columns = df.columns
print(norm)

import matplotlib.pyplot as plt
plt.figure(figsize=(30,5))
#plt.plot(norm["times"],norm["ROC-LOC"]*2)
#plt.plot(norm["times"],norm["LOC-ROC"]*2)
#plt.plot(norm["times"],norm["F2-F4"]*2)
#plt.plot(norm["times"],norm["F4-C4"]*2)
#plt.plot(norm["times"],norm["C4-P4"]*2)
#plt.plot(norm["times"],norm["P4-O2"]*3)
#plt.plot(norm["times"],norm["F1-F3"]*3)
#plt.plot(norm["times"],norm["F3-C3"]*3)
#plt.plot(norm["times"],norm["C3-P3"]*3)
#plt.plot(norm["times"],norm["P3-O1"]*3)
#plt.plot(norm["times"],norm["C4-A1"])
#plt.plot(norm["times"],norm["EMG1-EMG2"]*3)
#plt.plot(norm["times"],norm["ECG1-ECG2"])
#plt.plot(norm["times"],norm["TERMISTORE"])
#plt.plot(norm["times"],norm["TORACE"])
#plt.plot(norm["times"],norm["ADDOME"])
#plt.plot(norm["times"],norm["Dx1-DX2"]*2)
#plt.plot(norm["times"],norm["SX1-SX2"])
#plt.plot(norm["times"],norm["Posizione"])
#plt.plot(norm["times"],norm["HR"]*2)
#plt.plot(norm["times"],norm["SpO2"]*3)
plt.plot(norm["times"],(norm["sleepstage"]))

df[["times","sleepstage","LOC-ROC","ROC-LOC","F2-F4","F4-C4","C4-P4","P4-O2","F1-F3","F3-C3","C3-P3","P3-O1","EMG1-EMG2","TORACE","Dx1-DX2","SX1-SX2","HR"]]